version: '3.8'

services:
    web:
        build:
            context: .
            dockerfile: ./compose/Dockerfile
        image: fastapi_app
        command: /web_start
        volumes:
            - ./project:/usr/src/app
        ports:
            - 8004:8000
        env_file:
            - .env/.dev-sample
        depends_on:
            - web-db
            - redis

    web-db:
        build:
            context: .
            dockerfile: ./db/Dockerfile
        expose:
            - 5432
        env_file:
            - .env/.dev-sample

    redis:
        image: redis:7-alpine

    celery_worker:
        build:
            context: .
            dockerfile: ./compose/Dockerfile
        image: fastapi_celery_worker
        command: /worker_start
        volumes:
            - ./project:/usr/src/app
        env_file:
            - .env/.dev-sample
        depends_on:
            - redis
            - web-db

    celery_beat:
        build:
            context: .
            dockerfile: ./compose/Dockerfile
        image: fastapi_celery_beat
        command: /beat_start
        volumes:
            - ./project:/usr/src/app
        env_file:
            - .env/.dev-sample
        depends_on:
            - redis
            - web-db

    flower:
        build:
            context: .
            dockerfile: ./compose/Dockerfile
        image: fastapi_celery_flower
        command: /flower_start
        volumes:
            - ./project:/usr/src/app
        env_file:
            - .env/.dev-sample
        ports:
            - 5557:5555
        depends_on:
            - redis
            - web-db
