version: '3.8'

services:
    web:
        build:
            context: .
            dockerfile: ./compose/Dockerfile
        command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
        volumes:
            - ./project:/usr/src/app
        ports:
            - 8004:8000
        env_file:
            - .env/.dev-sample
        depends_on:
            - web-db

    web-db:
        build:
            context: ./project/db
            dockerfile: Dockerfile
        expose:
            - 5432
        env_file:
            - .env/.dev-sample

    redis:
        image: redis:7-alpine

    celery_worker:
        build:
            context: .
            dockerfile: ./compose/Dockerfile
        image: fastapi_celery_example_celery_worker
        command: /start-celeryworker
        volumes:
            - ./project:/usr/src/app
        env_file:
            - .env/.dev-sample
        depends_on:
            - redis
            - web-db

    celery_beat:
        build:
            context: .
            dockerfile: ./compose/Dockerfile
        image: fastapi_celery_example_celery_beat
        command: /start-celerybeat
        volumes:
            - ./project:/usr/src/app
        env_file:
            - .env/.dev-sample
        depends_on:
            - redis
            - web-db
    flower:
        build:
            context: .
            dockerfile: ./compose/Dockerfile
        image: fastapi_celery_example_celery_flower
        command: /start-flower
        volumes:
            - ./project:/usr/src/app
        env_file:
            - .env/.dev-sample
        ports:
            - 5557:5555
        depends_on:
            - redis
            - web-db
